server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

payme:
  id: 64d381a275b7ebd897177498
  key: qqukMeDCVk@wR3nG4F#W#M5ZdwVHsyNnAEPs
  url: https://checkout.paycom.uz
  call-back-url: https://7013-2a0d-5600-8-6001-00-4d24.ngrok-free.app/payments/merchant
  min-amount: 0
  account: order_id
