server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

payme:
  id: 64d381a275b7ebd897177498
  key: nsoVHFesiBdQf3@nD0FGAsbQo&ozAuOzwxOQ
  url: https://checkout.paycom.uz
  call-back-url: https://3adb-82-215-108-94.ngrok.io/payments/merchant
  min-amount: 0
  account: order_id
