server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payme
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

payme:
  id: 64d381a275b7ebd897177498
  key: qqukMeDCVk@wR3nG4F#W#M5ZdwVHsyNnAEPs
  url: https://checkout.paycom.uz
  call-back-url: http://91.186.197.205/api/payments/merchant
  min-amount: 1000
  account: order_id
